### ISSUE TITLE
Progress meter/bar

### ISSUE THREAD

**Issue by alyxender** [LEARNAcademy/prework-frontend#4]
As a logged in user, I need to be able to see my progress in a visual object (meter), so that I can know how far along I am with the course.

Need:
1. Number of Modules per Section
2. Number of Sections (Typing, Git, Terminal, HTML, CSS, JS)
3. Completed message

**Comment by art-ortega** [comment]
- User is not able to view their total course completion on bottom right
- Progress bar rendering module info dynamically on top of bar
