### ISSUE TITLE
Content Delivery

### ISSUE THREAD

**Issue by alyxender** [LEARNAcademy/prework-frontend#6]
As a logged in user, I need to see the lesson content and have the ability to interact with the lecture so that I can be well informed about the topic before I start answering challenge questions.

Need:
1. Store lesson (modules) and associate with related questions
2. Display both text and images (and videos)
3. Provide answer input for an interactive lecture (IDE, String, Radios, etc)

**Comment by art-ortega** [comment]
- User is able to view Modules and their respective lessons. 
- Both text and images are able to be viewed by the user once data is seeded in
- Answer input is handled by radio buttons and IDE, already implemented( need IDE next)
